### ISSUE TITLE
v6.0.8 and v6.0.8b ImportError: No module named PyQt4.Qt

### ISSUE THREAD

**Issue by willin** [psyrendust/dedrm-ebook-tools#13]
```
calibre, version 2.35.0
错误： 未处理的异常: <b>ImportError</b>:No module named PyQt4.Qt

calibre 2.35 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 289, in double_clicked
  File "site-packages\calibre\gui2\preferences\plugins.py", line 370, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 154, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 494, in config_widget
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.dedrm.config", line 12, in <module>
ImportError: No module named PyQt4.Qt
```

**Comment by latot** [comment]
+1
Linux in the same

**Comment by Gattermeier** [comment]
Calibre is using PyQt5, this should be updated in the config.py

**Comment by latot** [comment]
Thx!
